# Build and deploy Docker images on master merge

name: Build Images
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    env:
      LATEST: 1.16.4
    strategy:
      matrix:
        go-version: [1.16.4, 1.15.12]
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image - Go ${{ matrix.go-version }}
        run: |
          tags=$(./tools/get-image-tag --latest $LATEST ${{ matrix.go-version }})
          docker build $tags -f Dockerfile . --build-arg GO_VERSION=${{ matrix.go-version }} \
      - name: Push Image - Go ${{matrix.go-version}}
        run: |
          for img in $(./tools/get-image-tag --latest $LATEST --list ${{ matrix.go-version }}); do
            echo "Pushing $img...";
            docker push $img;
          done
